### ISSUE TITLE
Update bookmark older PNG images in order to fix the failing bookmark tests.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1089]
Any test case that is using this image as a step to check a bookmark added is failing. The UI has changed such that the message associated with the star turning blue has changed location in Beta.  Update this image and many of the bookmark test case should be good to go.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1089.

Please review.

Thank You

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1089.

Please review.

Thank You

**Comment by tracywalker** [comment]
Ionut, The following are still failing for me:

Linux: change_bookmark_location

Mac: change_bookmark_location, copy_context_menu, cut_context_menu and bookmarks_toolbar_sorted_by name

Windows: bookmark_from_private_browsing, bookmark_via_text_file_url, export_bookmarks_to_html and remove_tags_from_a_bookmark

Also, export_bookmarks_to_html is leaving behind dialogs and the Places window. It is covering the home button, such that at the end of the test Iris believes the browser is closed and moves on to the next test.

**Comment by IonutBudeanu** [comment]
Hi Tracy,

Linux: Problem fixed.

Mac: Everything works fine for me, all the tests have been passed. I don't know what's happening on your machine :(

Windows: I fixed the bookmark_via_text_file_url and export_bookmarks_to_html but other ones works just fine for me.

Also I fixed the problem with dialogs for export_bookmarks_to_html.

Please take a look.

Thank You

**Comment by tracywalker** [comment]
code approved with changes.
