### ISSUE TITLE
Develop test case: Links can be bookmarked via context menu.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#118]
https://testrail.stage.mozaws.net/index.php?/cases/view/4143

**Comment by IonutBudeanu** [comment]
Fixed in https://github.com/mozilla/iris/tree/issue_118

Please review.

Thank You

**Comment by tracywalker** [comment]
I made one correction in image declarations that you missed.
code approved

**Comment by IonutBudeanu** [comment]
Thank You
