### ISSUE TITLE
Linux: Test change_search_engine_positions kills Iris

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1200]
The browser is moved to the very bottom of the screen, almost invisible. It is unresponsive because there is some sort of modal dialog open, but it's not clear which one.

Line 100 starts a loop that never exits. It just scrolls the window down forever, looking for a pattern that never appears. 

This part of the test should be rewritten. We should avoid`while` loops and use the normal `exists`, `wait` methods etc. when possible, as they will time out no matter what happens. Otherwise, we have a test case that has the potential to ruin the Iris run and never recover.

**Comment by IonutBudeanu** [comment]
The problem in this test was that while block had no end loop statement if the pattern is not found.

Here we need a while block because the scroll_down() function needs to know when looking through  the options when the Google engine is reached for example, no matter what is the number of the options that needs to be scrolled (in general displayed options upon writing 'moz' in the search bar are between 8 and 10).

That's why i changed a little bit the while statement to run for maximum 10 times until the pattern is found or not.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1200.

Please review.

Thank You

**Comment by mwobensmith** [comment]
Merged in #1248. 

Test still fails, because it has been dragged to the bottom of the screen and the patterns can't be found. However, it no longer blocks the run, so that's better.
