### ISSUE TITLE
Investigate and fixes a few failing tests on Windows 10

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1309]
In the last cronjob report it can be noticed that some tests are failing.

The following tests did not pass:

- change_search_engine_positions
- focus_settings_gear_and_click_a_search_result
- key_navigation_high_contrast_theme
- more_search_engine_can_be_added
- one_off_searches_displayed_in_awesomebar
- one_off_searches_in_private_window
- perform_a_search_by_keyboard_only
- remove_checks_from_search_engines
- right_left_keys_in_awesomebar
- search_in_new_tab_using_one_off_context_menu
- two_selections_at_the_same_time
- remove_tags_from_a_bookmark
- browser_controls_upper_corner

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1309.

Some of these fixes probably will be valid for the other platforms too.

Please review.

Thank You

**Comment by tracywalker** [comment]
Ionut,

All of the tests that look at the search engines in the one off list are still failing for me. As I suspected, 0.5 seconds for image search time is too short.  He is what I suggest;  Key.DOWN through the search suggests list in a separate iterator a fixed number of times  (<- make that a little reusable function).  Then start another iterator around the exists check for the one off pattern string under test with a time of 2 seconds for exists check.

**Comment by tracywalker** [comment]
def key_through_suggestion_list()
     i = 1
     while i < 11:
         type(Key.DOWN)
         i += 1

You could make the second iterator a function too.  pass in the pattern and the search engine it represents.   
def find_one_off_search(pattern, site)
    max_attempts = 7
    while attempts > 0;
        if exists(pattern, 2):
            max_attempts = 0
        max_attempts = -= 1
    expected = region.exists(pattern, 5)
    assert_true(self, expected, 'The search engine in focus is ',  site, '.')

**Comment by tracywalker** [comment]
I pushed my changes to issue_1309 branch.  All the awesomebar tests work on Mac. 

However, several tests are failing on Linux:
change_search_engine_positions
disable_web_search_awesomebar
key_navigation_high_contrast_theme
one_off_searches_in_private_window
search_engine_can_be_added
search_in_new_tab_using_one_off_context_menu

Linux is behaving inconsistently with how many search suggest items it presents. Sometimes it's 8 sometimes 10 in the list.  I'll investigate further. 

Not all of the above failures are related to my changes.  I'll investigate those as well.

I am unable to work on Windows as there is a pipenv install error to be investigated and fixed. :(

**Comment by tracywalker** [comment]
I thought about these one off search test cases that are keyboarding through the one off search engine lists to get to desired positions.  I believe we should **not** be doing this, for the most part, in these test cases.  There are variations in the list length and number of search engines which make the steps unreliable.  I'm going to change the test cases to directly find the search engines with pattern matching.  The only test cases, in this group, that should remain heavily reliant on keyboard navigation are the few case that are actually testing the keyboard navigation.

**Comment by tracywalker** [comment]
hmmm, actually, the above suggestion adds a different level of complexity.  I think we can solve this by not keying down through the search suggests list (which can vary in length).  Instead, let's key up to get directly in the one off search engine bar, then look for the desired search engine under test with the key_to_one_off_search(pattern) function and adjust accordingly based on position of ebay (present or not).

**Comment by tracywalker** [comment]
All tests pass on Mac. 
The follow still fail on Linux.
- key_navigation_high_contrast_theme
- remove_checks_from_search_engines
- search_engine_can_be_added

I am still blocked on Windows by a curious pipenv install error.

Matt, please review the latest patch in branch issue_1039.  thank you.
