### ISSUE TITLE
Wikipedia web compat test should be disabled

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#522]
LIne 13 of this test case is commented out:

`#self.exclude = Platform.ALL`

Either the comment should be deleted, or the test gets turned off. However, since the rest of the test case still has issues (a `print` statement in line 28, double-quotes in method calls instead of single quotes, remove comment on line 83) and seems to have intermittent failures, it should really just be disabled.

**Comment by mwobensmith** [comment]
I think I am responsible for some of the problem code on this test. Plus, it causes the same problems I have in #521, so I might as well investigate.

**Comment by tracywalker** [comment]
instead was fixed and re-enabled by https://github.com/mozilla/iris/pull/550

**Comment by mariusandreifilip** [comment]
Test still fails on the text search and as a consequence I updated it to use patterns

**Comment by silviuFlorin** [comment]
Fixed some typos, replaced type with paste due to some instabilities. Test now passes. Code approved.
